name: afagent
channels:
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
      - mcp
      - openai
      - openai-agents
      - pillow
      - psutil
      - pyperclip
      - python-docx
      - pytest
      - pywinauto
